### ISSUE TITLE
Ticket 1: Implement Speech Bubble Tails (Pointers)

### ISSUE THREAD

**Issue by joeloverbeck** [joeloverbeck/living-narrative-engine#2306]
## Ticket 1: Implement Speech Bubble Tails (Pointers)

**Description:**
Enhance the visual appearance of speech bubbles by adding a triangular "tail" or "pointer." This tail should visually connect the speech bubble to the speaker's portrait. The tail should only be visible if a portrait is associated with the speech entry.

**Acceptance Criteria:**
1.  A triangular tail appears on speech bubbles when a `speech-portrait` is present within the `.speech-entry`.
2.  The tail correctly points towards the portrait (left side by default for NPC, right side for Player if Player vs. NPC distinction is implemented and reverses layout).
3.  The tail's border and fill color match the speech bubble's border (`--speech-border-color` or `--player-speech-border-color`) and background (`--speech-bg-color` or `--player-speech-bg-color`) respectively.
4.  The tail is not present if the `.speech-entry` has the class `.no-portrait` or lacks `.has-portrait`.
5.  The tail's appearance is consistent and well-proportioned with the bubble.

**Tasks:**

1.  **Modify `css/components/_speech-bubbles.css`:**
    * Ensure the `.speech-bubble` class has `position: relative;` to serve as a positioning context for the tail pseudo-elements.

        ```css
        /* In css/components/_speech-bubbles.css */
        .speech-bubble {
            /* ... existing styles ... */
            position: relative;
        }
        ```

    * **NPC/Default Tail (Points Left):** Add CSS rules for the `::before` (border) and `::after` (fill) pseudo-elements for speech bubbles associated with a portrait. These styles should target `.speech-entry.has-portrait .speech-bubble`.

        * **Tail Border (`::before`):**
            ```css
            .speech-entry.has-portrait .speech-bubble::before {
                content: "";
                position: absolute;
                width: 0;
                height: 0;
                border-style: solid;
                /* Tail pointing left */
                border-width: 10px 15px 10px 0; /* top, right, bottom, left values for a left-pointing triangle */
                border-color: transparent var(--speech-border-color) transparent transparent; /* Uses NPC speech border color */
                top: 15px; /* Adjust for vertical alignment. E.g., 15px from the top of the bubble. */
                left: -15px; /* (equal to border-width-right of the tail) Positions it just outside the bubble's left edge. */
                z-index: 0; /* Ensures it's behind the bubble's main border if they touch. */
            }
            ```

        * **Tail Fill (`::after`):**
            ```css
            .speech-entry.has-portrait .speech-bubble::after {
                content: "";
                position: absolute;
                width: 0;
                height: 0;
                border-style: solid;
                /* Tail pointing left, slightly smaller than ::before to create the border effect */
                border-width: 8px 13px 8px 0; /* Adjust top/right/bottom/left based on desired border thickness */
                border-color: transparent var(--speech-bg-color) transparent transparent; /* Uses NPC speech background color */
                top: 17px;  /* (top of ::before + (border-width-top of ::before - border-width-top of ::after)) */
                left: -13px; /* Position to align with the ::before border. (left of ::before + approx. border thickness difference) */
                z-index: 1; /* Above the ::before pseudo-element but below bubble content. */
            }
            ```

2.  **Verify JavaScript (`src/domUI/speechBubbleRenderer.js`):**
    * Confirm that the `SpeechBubbleRenderer.js` correctly adds the `has-portrait` class to `.speech-entry` when a `portraitPath` is found and a portrait image is successfully created and appended. No changes should be needed to the JS for this specific ticket if this class is already being reliably added.

3.  **Testing:**
    * Test speech bubbles from NPCs (or any entity with a portrait that isn't the player) to ensure the left-pointing tail appears correctly.
    * Test speech bubbles that have no portrait to ensure no tail appears.
    * Verify tail colors match the bubble's current theme colors for border and background.
    * Check for any visual glitches, like the tail overlapping the bubble's main border incorrectly.

**Affected Files:**
* `css/components/_speech-bubbles.css`
* `css/themes/_default-theme.css` (referenced for variables, no direct changes for this ticket unless new variables were chosen for tails, which is not the current plan).

**Notes/Considerations:**
* The `top` positioning values (e.g., `15px`, `17px`) for the pseudo-elements might need adjustment based on the padding and line-height of the `.speech-bubble` to ensure the tail points from a visually pleasing vertical position on the bubble.
* This ticket does *not* cover tails for player-specific bubbles that might point in the opposite direction. That will be handled in the "Player vs. NPC Distinction" ticket. If that ticket is implemented first, the tail direction logic here might need to be revisited or a more general tail approach that can be flipped might be used. For now, this implements the default left-pointing tail.
* The `z-index` values are assigned assuming the bubble content itself (text) will naturally be above these pseudo-elements. If text is ever obscured, adjustments to `z-index` on `.speech-bubble` content elements or the bubble itself may be needed.
