### ISSUE TITLE
Ticket 2: Add Enhanced Shadows to Speech Bubbles

### ISSUE THREAD

**Issue by joeloverbeck** [joeloverbeck/living-narrative-engine#2307]
## Ticket 2: Add Enhanced Shadows to Speech Bubbles

**Description:**
Apply a box-shadow directly to the `.speech-bubble` elements to give them more visual depth and make them "pop" from the chat panel background. This will enhance their prominence.

**Acceptance Criteria:**
1.  A `box-shadow` is applied to all `.speech-bubble` elements (both NPC and Player).
2.  The shadow style is subtle yet effective in providing a sense of depth.
3.  The shadow intensity is consistent and looks good with the current theme.
4.  The implementation preferably uses a new CSS variable for the shadow style to allow for easy theming.

**Tasks:**

1.  **Define a New CSS Variable for Speech Bubble Shadow (Recommended):**
    * **File:** `css/themes/_default-theme.css`
    * **Action:** In the `:root` selector, add a new variable for the speech bubble shadow. This provides better control and themability than reusing generic shadows like `--shadow-sm` if a specific look is desired.
        ```css
        /* In css/themes/_default-theme.css */
        :root {
            /* ... existing color, font, spacing, border, shadow variables ... */
            --shadow-sm: 0 2px 4px rgba(0, 0, 0, 0.06);
            --shadow-md: 0 5px 10px rgba(0, 0, 0, 0.1);
            --shadow-lg: 0 15px 25px rgba(0, 0, 0, 0.15);

            /* NEW: Specific shadow for speech bubbles */
            --shadow-speech-bubble: 0 3px 6px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0,0,0,0.08);

            /* ... rest of the variables ... */
        }
        ```
        * *Note:* The example value `0 3px 6px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08);` is a suggestion. Adjust as needed for the desired visual effect. It's slightly more pronounced than the existing `--shadow-sm`.

2.  **Apply the Box Shadow to `.speech-bubble`:**
    * **File:** `css/components/_speech-bubbles.css`
    * **Action:** Add the `box-shadow` property to the `.speech-bubble` style rule, using the new variable.

        ```css
        /* In css/components/_speech-bubbles.css */
        .speech-bubble {
            /* ... existing styles (background-color, color, padding, border-radius, position: relative, etc.) ... */
            box-shadow: var(--shadow-speech-bubble);
            /* Ensure a transition is present if hover effects might also alter shadows (see Ticket 7) */
            transition: transform 0.15s ease-out, box-shadow 0.15s ease-out, background-color 0.15s ease-out;
        }
        ```
        *(Self-correction: Added transition property here proactively, as it's good practice if shadows might change on hover, which is a subsequent ticket).*

3.  **Testing:**
    * Verify that both NPC and Player speech bubbles display the new shadow.
    * Check that the shadow provides a noticeable but not overly distracting depth effect.
    * Ensure the shadow looks consistent across different bubble content lengths and screen sizes.
    * Confirm that the shadow does not negatively interact with other elements (e.g., bubble tails, portraits).

**Affected Files:**
* `css/components/_speech-bubbles.css`
* `css/themes/_default-theme.css`

**Notes/Considerations:**
* The `li.message-speech` element already has a `box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);`. Applying a shadow directly to the `.speech-bubble` (the actual visual bubble) allows for more targeted control and can be slightly different if desired. If the `li.message-speech` shadow is sufficient or preferred, this ticket might be adjusted to ensure that shadow is consistently applied or enhanced, rather than adding a new one to `.speech-bubble`. However, styling `.speech-bubble` directly is generally more precise for the bubble's appearance.
* If a `transition` property is added to `.speech-bubble` for hover effects later, ensure `box-shadow` is included in the transition properties if its appearance changes on hover.
