### ISSUE TITLE
Ticket 3: Implement Border Refinements for Speech Bubbles

### ISSUE THREAD

**Issue by joeloverbeck** [joeloverbeck/living-narrative-engine#2308]
## Ticket 3: Implement Border Refinements for Speech Bubbles

**Description:**
Refine the border styling of `.speech-bubble` elements to ensure consistency with the theme's standard border width and to give the bubbles a softer, more "bubbly" appearance by adjusting the border radius.

**Acceptance Criteria:**
1.  The `border-width` of `.speech-bubble` elements uses the theme's global `--border-width` variable (currently `2px`).
2.  The `border-radius` of `.speech-bubble` elements is increased, preferably using the theme's `--border-radius-lg` variable (currently `12px`), to achieve a rounder look.
3.  These changes apply consistently to both NPC and Player speech bubbles.
4.  The updated border styling integrates well with other visual elements like shadows and tails.

**Tasks:**

1.  **Update `border-width` for `.speech-bubble`:**
    * **File:** `css/components/_speech-bubbles.css`
    * **Action:** Modify the `.speech-bubble` style rule to use `var(--border-width)` for its `border-width` property. The `border-style` (solid) and `border-color` (var(--speech-border-color)) should remain as they are, only the width needs to be explicitly set to use the variable.

        ```css
        /* In css/components/_speech-bubbles.css */
        .speech-bubble {
            /* ... existing styles (background-color, color, padding, box-shadow, position: relative, etc.) ... */
            /* Current border property might be like: border: 1px solid var(--speech-border-color); */
            /* Update to specify width using the variable: */
            border-width: var(--border-width);
            border-style: solid; /* Assuming it's solid, retain or set explicitly */
            border-color: var(--speech-border-color); /* Retain existing variable for NPC bubbles */
            /* border-radius will be updated next */
            /* ... other existing styles ... */
        }
        ```
        * *Note:* If the existing `border` shorthand is `border: 1px solid var(--speech-border-color);`, you'll change it to separate properties or ensure the `border` shorthand correctly incorporates `var(--border-width)`. Using individual properties as shown above is clearer for this change.

2.  **Update `border-radius` for `.speech-bubble`:**
    * **File:** `css/components/_speech-bubbles.css`
    * **Action:** Change the `border-radius` property for `.speech-bubble` to use `var(--border-radius-lg)`. The current `_default-theme.css` defines `--border-radius-lg` as `12px`, while `--border-radius-md` (currently used via `--border-radius-standard`) is `6px`.

        ```css
        /* In css/components/_speech-bubbles.css */
        .speech-bubble {
            /* ... existing styles including updated border-width, border-style, border-color ... */
            border-radius: var(--border-radius-lg); /* Changed from var(--border-radius-standard) or var(--border-radius-md) */
            /* ... other existing styles ... */
        }
        ```

3.  **Testing:**
    * Verify that speech bubbles now have a `2px` border width (or whatever `--border-width` is set to).
    * Confirm that speech bubbles have a `12px` border radius (or whatever `--border-radius-lg` is set to), appearing rounder.
    * Check that these changes apply to both default/NPC bubbles and player-specific bubbles (once player-specific styles are implemented, ensuring they don't unintentionally override these base refinements unless desired).
    * Ensure the new border style looks good with the shadows and tails (if implemented).

**Affected Files:**
* `css/components/_speech-bubbles.css`
* `css/themes/_default-theme.css` (referenced for variables `--border-width` and `--border-radius-lg`).

**Notes/Considerations:**
* The `border-color` for player-specific speech bubbles (`--player-speech-border-color`) will be handled in the "Player vs. NPC Distinction" ticket. This ticket focuses on the width and radius for all bubbles.
* Ensure that increasing the `border-width` does not negatively impact the positioning or appearance of the speech bubble tails, especially the inner fill part of the tail (`::after` pseudo-element), which might need slight positional adjustments if the border becomes significantly thicker. The planned `2px` from `1px` should be minor enough.
