### ISSUE TITLE
Ticket 4: Implement Clear Player vs. NPC Speech Bubble Distinction

### ISSUE THREAD

**Issue by joeloverbeck** [joeloverbeck/living-narrative-engine#2309]
## Ticket 4: Implement Clear Player vs. NPC Speech Bubble Distinction

**Description:**
Visually differentiate speech bubbles originating from the player character versus those from NPCs/AI entities. This involves reversing the layout for player speech (e.g., portrait on the right), applying distinct styling (colors, etc.), and ensuring any speech bubble tails point correctly.

**Acceptance Criteria:**
1.  A new class, e.g., `.player-speech`, is added to the `.speech-entry` div when the speech originates from the player character.
2.  CSS rules for `.speech-entry.player-speech` correctly reverse the layout (portrait on the right, bubble on the left).
3.  Player speech bubbles use distinct background, text, and border colors, defined via new CSS variables in the theme file.
4.  If speech bubble tails (Ticket 1) are implemented, the tail for player speech bubbles correctly points towards the player's portrait (i.e., to the right).
5.  Text content (speaker intro, quoted text, action text) within player speech bubbles maintains good contrast and readability against the player bubble's background.

**Tasks:**

**Phase 1: Define Player-Specific CSS Variables**

1.  **Edit `css/themes/_default-theme.css`****:**
    * Add new CSS variables within the `:root` selector for player speech bubble styling.
        ```css
        /* In css/themes/_default-theme.css */
        :root {
            /* ... existing variables ... */

            /* NEW: Variables for Player Speech Bubbles */
            --player-speech-bg-color: var(--accent-color-secondary); /* Example: Use the theme's orange accent */
            --player-speech-text-color: #FFFFFF; /* Example: White text for good contrast on orange */
            --player-speech-border-color: #c0392b; /* Example: A darker orange/red, or var(--accent-color-secondary) */
            /* Ensures action text within player bubble also has good contrast if it needs a specific color */
            --player-speech-action-text-color: var(--player-speech-text-color); /* Default to same as main player text color */

            /* ... rest of the variables ... */
        }
        ```

**Phase 2: Implement Player-Specific CSS Styles**

1.  **Edit `css/components/_speech-bubbles.css`****:**
    * **Reverse Layout for Player Speech:**
        ```css
        /* In css/components/_speech-bubbles.css */
        .speech-entry.player-speech {
            flex-direction: row-reverse; /* Moves portrait to the right, bubble to the left */
        }

        .speech-entry.player-speech .speech-portrait {
            margin-right: 0; /* Remove default right margin */
            margin-left: var(--spacing-md); /* Add space between bubble (now on left) and portrait (on right) */
        }
        ```

    * **Style Player Speech Bubble:**
        ```css
        .speech-entry.player-speech .speech-bubble {
            background-color: var(--player-speech-bg-color);
            color: var(--player-speech-text-color);
            border-color: var(--player-speech-border-color);
            /* Inherits border-width, border-radius, box-shadow, etc. from .speech-bubble base styles */
        }
        ```

    * **Adjust Tail Direction for Player Speech Bubble (if tails from Ticket 1 are implemented):**
        The tail should now point to the right.
        ```css
        /* Tail pointing right (for player speech bubble with portrait on the right) */
        .speech-entry.player-speech.has-portrait .speech-bubble::before {
            /* Overrides the default left-pointing tail */
            border-width: 10px 0 10px 15px; /* top, right, bottom, left values for a right-pointing triangle */
            border-color: transparent transparent transparent var(--player-speech-border-color); /* Uses player speech border color */
            left: auto; /* Reset left positioning */
            right: -15px; /* Positions it just outside the bubble's right edge */
            /* top and z-index can remain the same as the default tail from Ticket 1 */
        }

        .speech-entry.player-speech.has-portrait .speech-bubble::after {
            /* Overrides the default left-pointing tail fill */
            border-width: 8px 0 8px 13px; /* top, right, bottom, left */
            border-color: transparent transparent transparent var(--player-speech-bg-color); /* Uses player speech background color */
            left: auto; /* Reset left positioning */
            right: -13px; /* Position to align with the ::before border */
            /* top and z-index can remain the same as the default tail from Ticket 1 */
        }
        ```

    * **Ensure Text Contrast within Player Bubble:**
        Style the text elements within the player's speech bubble to use the player-specific text colors.
        ```css
        .speech-entry.player-speech .speech-bubble .speech-speaker-intro,
        .speech-entry.player-speech .speech-bubble .speech-quoted-text {
            color: var(--player-speech-text-color);
        }

        .speech-entry.player-speech .speech-bubble .speech-action-text {
            color: var(--player-speech-action-text-color);
            /* font-style: normal; and font-weight: bold; are inherited from the base .speech-action-text rule */
        }
        ```

**Phase 3: Modify `SpeechBubbleRenderer.js` to Add `.player-speech` Class**

1.  **Edit `src/domUI/speechBubbleRenderer.js`****:**
    * In the `renderSpeech` method, add logic to determine if the `entityId` belongs to the player. If it does, add the `player-speech` class to the `speechEntryDiv`.

        ```javascript
        // In src/domUI/speechBubbleRenderer.js, within the renderSpeech method:

        // ... (after speechEntryDiv is created)
        // const speechEntryDiv = this.#domElementFactory.create('div', {cls: 'speech-entry'});

        // Determine if the speaker is the player
        // ASSUMPTION: this.#entityDisplayDataProvider.isPlayer(entityId) method exists or an equivalent mechanism
        // to identify the player entity will be implemented.
        // Example:
        // const isPlayer = this.#entityDisplayDataProvider.isPlayer(entityId);
        // --- OR ---
        // const currentPlayerId = this.#entityManager.getPlayerEntity()?.id; // Hypothetical
        // const isPlayer = entityId === currentPlayerId;

        // Placeholder for actual player identification logic:
        let isPlayer = false; // Default to false
        // TODO: Implement actual player identification logic here.
        // For example, if you have a known player ID:
        // if (entityId === 'playerCharacterInstance001') { // Replace with actual player ID or check method
        //     isPlayer = true;
        // }
        // A more robust way would be to ask a service:
        if (this.#entityDisplayDataProvider.isPlayer && typeof this.#entityDisplayDataProvider.isPlayer === 'function') {
             isPlayer = this.#entityDisplayDataProvider.isPlayer(entityId);
        } else if (this.#entityManager.isPlayerEntity && typeof this.#entityManager.isPlayerEntity === 'function') { // Alternative
             isPlayer = this.#entityManager.isPlayerEntity(entityId);
        } else {
            // Fallback or warning if no robust method exists yet.
            // For now, this example will not mark anyone as player unless logic is filled.
            this.logger.warn(`${this._logPrefix} Player identification mechanism not fully implemented. Player speech bubbles may not be styled correctly.`);
        }


        if (isPlayer) {
            speechEntryDiv.classList.add('player-speech');
        }

        // ... (rest of the method: portrait handling, appending bubble, etc.)
        ```
    * **Important:** The `TODO` comment above highlights where the actual player identification logic needs to be implemented. This is crucial for the `.player-speech` class to be applied correctly. This might involve adding a method like `isPlayer(entityId)` to `EntityDisplayDataProvider` or `EntityManager`, or retrieving a known player ID from a game state service.

**Testing:**
1.  Ensure speech from an entity identified as the "player" receives the `.player-speech` class.
2.  Verify player speech bubbles have the reversed layout (portrait right, bubble left).
3.  Confirm player speech bubbles use the distinct colors defined in `--player-speech-bg-color`, etc.
4.  If tails are implemented, check that the player's speech bubble tail points to the right.
5.  Check text readability and contrast for all parts of the player's speech bubble (intro, quote, action text).
6.  Verify that NPC speech bubbles remain styled as before (or with the default left-pointing tail if Ticket 1 is done).

**Affected Files:**
* `css/components/_speech-bubbles.css`
* `css/themes/_default-theme.css`
* `src/domUI/speechBubbleRenderer.js`
