### ISSUE TITLE
Ticket 5: Refine Action Text Emphasis & Add Entry Animations

### ISSUE THREAD

**Issue by joeloverbeck** [joeloverbeck/living-narrative-engine#2310]
## Ticket 5: Refine Action Text Emphasis & Add Entry Animations

**Description:**
This ticket covers two related enhancements:
1.  Ensure the existing typographic emphasis for "action text" (text within asterisks, e.g., `*The door creaks open*`) remains visually distinct and maintains good contrast within both standard NPC and player-specific speech bubbles.
2.  Implement a subtle entry animation for new speech bubbles to make their appearance on screen more polished and dynamic.

**Acceptance Criteria:**

* **Action Text Emphasis:**
    1.  The `.speech-action-text` style (bold, specific color) is clearly distinguishable from regular quoted text.
    2.  The color of `.speech-action-text` provides good contrast against the background of NPC speech bubbles (`--speech-bg-color`).
    3.  The color of `.speech-action-text` (using `--player-speech-action-text-color`) provides good contrast against the background of Player speech bubbles (`--player-speech-bg-color`).
* **Entry Animations:**
    1.  New speech bubbles (`.speech-entry` elements) animate into view (e.g., fade-in or fade-and-slide-in).
    2.  The animation is brief and subtle, not distracting from the content.
    3.  The animation plays smoothly.

**Tasks:**

**Part A: Refining Typographic Emphasis for Action Text**

1.  **Verify Existing Styles and Variables:**
    * **File:** `css/components/_speech-bubbles.css`
        * Confirm `.speech-action-text` base style:
            ```css
            .speech-bubble .speech-action-text {
                color: var(--speech-action-text-color); /* Default red */
                font-style: normal; /* Override italic from .speech-quoted-text */
                font-weight: bold; /* Make action text bold for emphasis */
            }
            ```
    * **File:** `css/themes/_default-theme.css`
        * Confirm default action text color:
            ```css
            :root {
                /* ... */
                --speech-action-text-color: #c0392b; /* Red for NPC bubbles */
                /* ... */
            }
            ```
        * Confirm player-specific action text color (from Ticket 4):
            ```css
            :root {
                /* ... */
                --player-speech-action-text-color: var(--player-speech-text-color); /* Defaulted to white for player */
                /* ... */
            }
            ```

2.  **Test Contrast:**
    * Visually inspect action text within NPC bubbles (red text on light purple background `--speech-bg-color: #f5eef8;`) for good readability.
    * Visually inspect action text within Player bubbles (white text on orange background `--player-speech-bg-color: var(--accent-color-secondary);`) for good readability.
    * *No CSS changes are anticipated here unless contrast issues are found.*

3.  **Optional: Minor Visual Tweak for Action Text (Use with Caution):**
    * **File:** `css/components/_speech-bubbles.css`
    * If additional emphasis is desired and does not harm readability, a very subtle text-shadow could be considered. *This is often not necessary and can clutter the text.*
        ```css
        /* In css/components/_speech-bubbles.css - OPTIONAL */
        /*
        .speech-action-text {
            // ... existing styles ...
            // text-shadow: 1px 1px 1px rgba(0,0,0,0.1); // Example: very subtle dark shadow
        }
        */
        ```

4.  **Verify JavaScript (`src/domUI/speechBubbleRenderer.js`):**
    * No changes anticipated. The current renderer logic correctly identifies `*action text*` and applies the `.speech-action-text` class.

**Part B: Entry Animations for Bubbles**

1.  **Define CSS Keyframes for Animations:**
    * **File:** `css/components/_speech-bubbles.css`
    * Add `@keyframes` rules for desired animations (e.g., at the end of the file).
        ```css
        /* In css/components/_speech-bubbles.css */

        @keyframes fadeInUpBubble {
            from {
                opacity: 0;
                transform: translateY(15px); /* Start bubble slightly lower */
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        @keyframes fadeInBubble {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }
        ```

2.  **Apply Animation to `.speech-entry`:**
    * **File:** `css/components/_speech-bubbles.css`
    * Modify the `.speech-entry` style rule to use one of the defined animations. The `forwards` keyword ensures the element retains the styles from the `to` state of the animation.
        ```css
        /* In css/components/_speech-bubbles.css */
        .speech-entry {
            /* ... existing styles (e.g., display: flex, margin-bottom, width) ... */
            animation: fadeInUpBubble 0.3s ease-out forwards;
            /* Or, for a simpler fade: */
            /* animation: fadeInBubble 0.25s ease-out forwards; */
        }
        ```

3.  **Testing Animations:**
    * Verify that new speech bubbles (both NPC and Player) animate into view smoothly.
    * Ensure the chosen animation (e.g., `fadeInUpBubble`) is brief (0.25s to 0.4s is usually good) and not jarring.
    * Confirm the `forwards` keyword is working, and bubbles remain visible after animating.

**Affected Files:**
* `css/components/_speech-bubbles.css`
* `css/themes/_default-theme.css` (for verifying color variables)
* `src/domUI/speechBubbleRenderer.js` (for verifying existing action text parsing, no changes planned)

**Notes/Considerations:**
* The primary goal for action text is **readability and clear differentiation**. Avoid over-styling.
* Entry animations should be subtle. If they feel too slow or too dramatic, adjust the duration and `transform` values.
* No JavaScript changes are required for the entry animation if it's applied directly to the `.speech-entry` class in CSS, as each new bubble element will naturally trigger its animation upon being added to the DOM and rendered.
