### ISSUE TITLE
Ticket 6: Implement Subtle Hover Effects for Speech Bubbles (Optional)

### ISSUE THREAD

**Issue by joeloverbeck** [joeloverbeck/living-narrative-engine#2311]
## Ticket 6: Implement Subtle Hover Effects for Speech Bubbles (Optional)

**Description:**
(Optional) Add very subtle visual feedback when the mouse cursor hovers over a `.speech-bubble` element. This is primarily for desktop users and should be implemented with caution to avoid distracting from the main content in a text-heavy interface.

**Acceptance Criteria:**
1.  When a speech bubble is hovered, a very subtle visual change occurs (e.g., slightly more pronounced shadow or a minimal scale increase).
2.  The hover effect is smooth, utilizing CSS transitions.
3.  The effect is not distracting or visually overwhelming.
4.  The effect applies to both NPC and Player speech bubbles.

**Tasks:**

1.  **Ensure `transition` Property on Base `.speech-bubble` Style:**
    * **File:** `css/components/_speech-bubbles.css`
    * **Action:** If not already present (e.g., from Ticket 2 for shadow transitions), add or update the `transition` property on the main `.speech-bubble` style rule to include properties that might change on hover (like `box-shadow` or `transform`).

        ```css
        /* In css/components/_speech-bubbles.css */
        .speech-bubble {
            /* ... existing styles (background-color, color, padding, border-radius, box-shadow, etc.) ... */
            /* Ensure relevant properties are included in the transition for smoothness */
            transition: transform 0.15s ease-out, box-shadow 0.15s ease-out, background-color 0.15s ease-out;
            /* Add other properties if they change on hover, e.g., border-color */
        }
        ```

2.  **Implement CSS for Hover Effect on `.speech-bubble:hover`:**
    * **File:** `css/components/_speech-bubbles.css`
    * **Action:** Add a new style rule for `.speech-bubble:hover`. Choose *one* of the following subtle effects, or experiment with similar minimal changes.

        * **Option A: Slightly More Pronounced Shadow:**
            If using `--shadow-speech-bubble` from Ticket 2 (e.g., `0 3px 6px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08);`), you could define a slightly deeper hover shadow or use an existing one like `--shadow-md`.
            ```css
            /* In css/components/_speech-bubbles.css - OPTION A */
            .speech-bubble:hover {
                /* Example: Using a slightly deeper shadow or a general "medium" shadow variable */
                box-shadow: 0 5px 10px rgba(0,0,0,0.15), 0 2px 4px rgba(0,0,0,0.1); /* Adjust values as needed */
                /* Or, if you have a theme variable like --shadow-md that fits: */
                /* box-shadow: var(--shadow-md); */
            }
            ```

        * **Option B: Very Slight Scale Increase:**
            ```css
            /* In css/components/_speech-bubbles.css - OPTION B */
            .speech-bubble:hover {
                transform: scale(1.01); /* Very minimal scale to avoid jitter or large shifts */
            }
            ```

3.  **Testing:**
    * Hover over various speech bubbles (NPC, Player, different lengths) on a desktop browser.
    * Evaluate if the effect is noticeable but not distracting.
    * Ensure the transition is smooth.
    * Check for any unintended layout shifts or performance issues (unlikely with these subtle effects, but good to be mindful).
    * **Crucially, decide if the effect adds positive value or just clutters the UI. If it's distracting, it's better to omit this feature.**

**Affected Files:**
* `css/components/_speech-bubbles.css`

**Notes/Considerations:**
* **Subtlety is Key:** For a text-based adventure game, the focus should remain on the text. Hover effects can easily become visual noise if not handled with extreme care.
* **User Preference/Setting:** For more advanced applications, such an effect could even be a user-configurable setting, but that's beyond the scope of this ticket.
* **Alternative:** Instead of a hover effect on the bubble itself, a subtle underline or background change on links *within* a bubble (if any interactive text elements are planned inside bubbles) might be more appropriate for indicating interactivity. This ticket, however, focuses on the bubble container.
