### ISSUE TITLE
Ticket 7: Implement "Thinking/Processing" Indicator (Advanced Feature)

### ISSUE THREAD

**Issue by joeloverbeck** [joeloverbeck/living-narrative-engine#2312]
## Ticket 7: Implement "Thinking/Processing" Indicator (Advanced Feature)

**Description:**
Introduce a visual indicator to provide feedback to the user when the AI is processing its turn (after the player has acted and before the AI's actions/speech are displayed) and potentially when the player is composing their turn (e.g., after typing in the input field or selecting an action but before confirming). This indicator should be subtle and not necessarily a "speech bubble."

**User Stories/Requirements:**

1.  **AI Processing:**
    * As an Admin/Player, I want to see a visual indicator when an AI entity is "thinking" or processing its turn, so I know the game is active and hasn't stalled.
    * This indicator should appear after the player's turn is submitted and an AI is expected to act.
    * It should disappear when the AI's actions/speech for the current turn begin to render.
2.  **Player Composing Turn (Optional Extension):**
    * As an Admin/Player, I might want to see a subtle indicator when my player character has pending input (text in the input field or a selected action) that has not yet been confirmed, so I have a visual cue of my uncommitted turn.
    * This indicator could appear when the player types in the command input or selects an action button.
    * It should disappear when the player confirms their turn (e.g., clicks "Confirm Action").
3.  **Visuals:**
    * The indicator should be visually distinct from speech bubbles (e.g., not a bubble shape with a tail).
    * It should be non-intrusive and not obscure important game information. Animated dots or a subtle spinner are common patterns.

**Proposed Implementation Areas & Tasks:**

**1. UI Element Design & Placement:**

* **Visuals:** A simple series of animated dots (e.g., three horizontally aligned dots that pulse or fade in/out sequentially) is recommended for subtlety.
* **Placement:**
    * **Option A (General):** A small, unobtrusive area, perhaps appended to the `#message-list` or `#outputDiv` below the last rendered message.
    * **Option B (Player-Specific):** If also used for player input state, it could appear near the `#speech-input` bar or directly below it.
    * The element should be created dynamically via JavaScript.
* **HTML (Conceptual - to be added via JS):**
    ```html
    <div id="processing-indicator" class="processing-indicator" style="display: none;" aria-live="polite" aria-label="Processing turn">
        <span class="dot"></span><span class="dot"></span><span class="dot"></span>
    </div>
    ```

**2. CSS Styling for the Indicator:**

* **File:** Create a new CSS file (e.g., `css/components/_processing-indicator.css`) and import it into `css/style.css`, or add to an existing relevant component file like `css/components/_messages.css`.
* **Styling:**
    * Style the `.processing-indicator` container (layout, padding, margins).
    * Style the `.dot` elements (size, color, border-radius, animation).
    * Ensure appropriate `display: none;` by default.
    ```css
    /* Example CSS */
    .processing-indicator {
        display: flex;
        align-items: center;
        justify-content: center; /* Or left, depending on placement */
        padding: var(--spacing-sm) 0; /* Adjust padding as needed */
        margin-top: var(--spacing-xs);
        /* Consider adding a subtle background or border if it needs to stand out more */
    }

    .processing-indicator .dot {
        width: 8px;
        height: 8px;
        margin: 0 3px;
        background-color: var(--secondary-text-color); /* Or a theme accent */
        border-radius: 50%;
        opacity: 0; /* Start invisible if animation handles fade-in */
        animation: processingDotsAnimation 1.4s infinite ease-in-out;
    }

    /* Stagger animation delays for the dots */
    .processing-indicator .dot:nth-child(1) {
        animation-delay: 0s;
    }
    .processing-indicator .dot:nth-child(2) {
        animation-delay: 0.2s;
    }
    .processing-indicator .dot:nth-child(3) {
        animation-delay: 0.4s;
    }

    @keyframes processingDotsAnimation {
        0%, 100% {
            opacity: 0.3;
            transform: scale(0.7);
        }
        50% {
            opacity: 1;
            transform: scale(1);
        }
    }
    ```

**3. JavaScript Logic (New Renderer/Controller):**

* **Create a new JavaScript class** (e.g., `ProcessingIndicatorController.js` in `src/domUI/`).
    * This class would extend `BoundDomRendererBase` or `RendererBase`.
    * It would be responsible for creating (if not in HTML), showing, and hiding the indicator element.
* **Dependencies:** Logger, DocumentContext, DomElementFactory, ValidatedEventDispatcher.
* **Show/Hide Methods:** Implement `showIndicator(type)` (where type could be 'ai' or 'player') and `hideIndicator()`.
* **Event Subscriptions:**
    * **For AI Processing:**
        * Subscribe to an event that signifies the start of AI turn processing (e.g., `AI_TURN_PROCESSING_STARTED` - this event would need to be defined and dispatched by your game engine/turn manager when it sends a request to the LLM).
        * Subscribe to an event that signifies the end of AI turn processing or when AI actions/speech are ready to be displayed (e.g., `AI_TURN_PROCESSING_ENDED`, or just before `DISPLAY_SPEECH_ID` for AI).
    * **For Player Input State (Optional Extension):**
        * Subscribe to `PLAYER_ACTION_SELECTED` (if you have such an event when an action button is clicked but not yet confirmed).
        * Listen to `input` events on `#speech-input` to show when text is present.
        * Subscribe to `PLAYER_TURN_SUBMITTED_ID` (or a similar event for turn confirmation) to hide the indicator.
* **DOM Manipulation:**
    * Use `DomElementFactory` to create the indicator elements if they aren't in the static HTML.
    * Append/remove or show/hide the indicator in the chosen location.

**4. Integration:**

* Instantiate `ProcessingIndicatorController` in your main UI setup (similar to other renderers).
* Ensure it's initialized and its event subscriptions are active.
* Define and dispatch the necessary custom events from your game engine/turn management logic to trigger the AI processing indicator.

**Affected Files (Potential):**
* **New JS File:** `src/domUI/ProcessingIndicatorController.js` (or similar)
* **New CSS File:** `css/components/_processing-indicator.css` (or additions to existing CSS)
* `css/style.css` (to import the new CSS)
* Your main UI setup/initialization script (to instantiate and initialize the new controller).
* Game engine / Turn manager (to dispatch new events like `AI_TURN_PROCESSING_STARTED`).

**Notes/Considerations:**
* **Event Design:** The success of the AI processing indicator heavily relies on well-defined events from your game's backend/engine logic. You'll need to design events like `AI_TURN_PROCESSING_STARTED` and `AI_TURN_PROCESSING_ENDED` (or integrate with existing LLM call/response events).
* **Player Indicator Complexity:** The player-side indicator can be tricky. Showing it on *any* input might be too noisy. It might be better to show it only when significant unconfirmed input exists (e.g., text + a selected action, or after a brief pause in typing).
* **Placement:** Consider the overall UI flow. If the indicator is appended to a scrolling log like `#message-list`, ensure it scrolls into view or is positioned fixedly but unobtrusively.
* **Accessibility:** Use `aria-live="polite"` on the indicator and provide a suitable `aria-label` if the visual cue alone isn't sufficient for all users.
* **Phased Approach:** Implement the AI processing indicator first. The player input indicator can be a subsequent enhancement.
